name: Docker Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]


jobs:
  build-api:
    uses: cctechwiz/typescript-monorepo/.github/workflows/build-publish.yml@main
    with:
      package: api
  build-ui:
    uses: cctechwiz/typescript-monorepo/.github/workflows/build-publish.yml@main
    with:
      package: ui
